"""Regression artifact emission (spec 19.10).

This is the product, not the byproduct. Prior repair work leaves a patched test
and a promise. ChronoTrace leaves a patched test *plus* a test that forces the
exact interleaving that used to fail, so a race that appeared once in a thousand
runs now reproduces every run, in milliseconds.

The guard is appended to the module it guards. That keeps the module's fixtures
— including the one managing the injected primitive's lifetime — in scope, and
puts the fix and its guard in the same reviewable diff.
"""

from __future__ import annotations

import ast
import re

__all__ = ["append_regression_test", "regression_test_name"]

_IMPORTS = "from chronotrace.schedule.harness import ScheduleHarness, force_order"


def regression_test_name(incident_id: str) -> str:
    """Return the generated test's function name for an incident."""
    slug = re.sub(r"[^0-9a-zA-Z]+", "_", incident_id).strip("_").lower()
    return f"test_chronotrace_regression_{slug}"


def append_regression_test(
    source: str,
    *,
    test_function: str,
    forced_order: list[str],
    incident_id: str,
    natural_flake_rate: float,
    gate_timeout_s: float = 5.0,
) -> str:
    """Append a deterministic forced-interleaving guard to a patched module.

    Args:
        source: The patched module source.
        test_function: Name of the test the race was found in.
        forced_order: Operation keys in the order that reproduces the race.
        incident_id: Incident this guard came from.
        natural_flake_rate: Rate the race appeared at before the repair, quoted
            in the docstring so the guard carries its own provenance.
        gate_timeout_s: Cap on each gate wait inside the guard.

    Returns:
        The module source with the guard appended.

    Raises:
        ValueError: ``test_function`` is not defined in ``source``.

    """
    parameters = _parameters_of(source, test_function)
    name = regression_test_name(incident_id)
    signature = ", ".join(parameters)
    call_args = ", ".join(parameters)
    order_literal = ", ".join(repr(key) for key in forced_order)
    body = f'''

@pytest.mark.asyncio
async def {name}({signature}) -> None:
    """Reproduce the interleaving that used to fail, deterministically.

    Generated by ChronoTrace for incident {incident_id}. Before the repair this
    race appeared in roughly {natural_flake_rate:.0%} of runs; this guard forces the
    exact ordering that caused it, so a regression fails here on every run
    rather than once in a while.
    """
    forced_order = [{order_literal}]
    harness = ScheduleHarness(forced_order, timeout_s={gate_timeout_s})
    with force_order(harness):
        await {test_function}({call_args})
    assert harness.reached == forced_order
'''
    patched = source if _IMPORTS in source else _insert_import(source)
    return patched.rstrip("\n") + "\n" + body


def _insert_import(source: str) -> str:
    lines = source.splitlines(keepends=True)
    last_import = 0
    for index, line in enumerate(lines):
        if line.startswith(("import ", "from ")):
            last_import = index
    lines.insert(last_import + 1, _IMPORTS + "\n")
    return "".join(lines)


def _parameters_of(source: str, function: str) -> list[str]:
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef) and node.name == function:
            return [argument.arg for argument in node.args.args]
    raise ValueError(f"{function!r} is not defined in the module")
